### PR TITLE
Set copyright in LICENSE.txt appendix

### PR DESCRIPTION
**Pull request by JamieSlome**
Adds xAI company name and year (date) to the copyright notice in Apache-2.0 license file 👍

### CODE REVIEW

**Comment by kyledmorgan** [comment]
Let's keep the placeholder values.  #TrueOpenSource

**Comment by Qu3tzal** [comment]
I think unfortunately if the copyright notice is invalid, it stays proprietary by default. We gain more by making sure the copyright notice is legally binding!

**Comment by soulteary** [comment]
ping @ibab @TobyPDE , Maybe it's worth merging.

**Comment by JamieSlome** [comment]
@msrb, agreed 👍 This appears to be guidance on how to use and template the license across the repository and its files rather than a means to actually specify the copyright holder.

I've seen a very mixed usage (e.g. [Snyk CLI](https://github.com/snyk/cli/blob/main/LICENSE)) on other repositories but it does help with quickly identifying the copyright holder centrally in the repo.

Happy to close this or keep open and wait for the maintainers opinion 🤝

**Review by BauerJustin — APPROVED** [review]
LGTM

**Comment by bedbad** [comment]
This highlights kinda a bigger major issue here. Since xAI is all about properly controlling vs liberating large models wouldn't their lawyers/team review, fix and clarify the license of their first major open release to the public?

**Review by FlusherDock1 — APPROVED** [review]
LGTM

**Comment by ibab** [comment]
Thank you Jamie, I agree with your assessment that specifying X.AI here is not strictly necessary

**Comment by JamieSlome** [comment]
@ibab - thanks for the review 👍 

In the longer term, it might be worth pulling a PR status check together to ensure new files include the Apache-2.0 header with the correct copyright statement.

**Pull request closed without merging**
